### ISSUE TITLE
Take screenshot of specific element for visual_matcher

### ISSUE THREAD

**Issue by samycici** [concretesolutions/magneton#15]

**Comment by mondaini** [comment]
Here is the robotframework code for the same feature: https://github.com/datakurre/robotframework-selenium2screenshots/blob/master/src/Selenium2Screenshots/keywords.robot#L599

**Comment by samycici** [comment]
http://startingwithseleniumwebdriver.blogspot.com.br/2014/10/taking-screen-shot-of-particular.html

**Comment by samycici** [comment]
http://stackoverflow.com/questions/10848900/how-to-take-partial-screenshot-frame-with-selenium-webdriver
